name: Deploy Proxy Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set Working Directory
        run: cd ./projx
        working-directory: ./projx  # Set the working directory to the "projx" subdirectory

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: npm start

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: projx

      - name: Clear npm cache
        run: npm cache clean --force
